=pod

=head1 NAME

envify - execute a command in the environment saved with envstore

=head1 SYNOPSIS

B<envify> I<command>...

=head1 DESCRIPTION

B<envify> loads the environment saved by B<envstore> and then executes I<command>.

=head1 LIMITATIONS

The envstore(1) limitations for null bytes apply here as well.

By default, newlines are not supported.  However, if you remove the newline from
the B<IFS> when calling envstore, newlines should work.
Example: C<< IFS=' ' envstore I<command> I<arguments>... >>

=head1 SEE ALSO

envstore(1)

=cut

vim:ft=pod
